services:
  db:
    shm_size: 128mb
    image: postgres
    env_file:
     - ./.env.docker
    volumes:
     - ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    env_file:
     - ./.env.docker
  celery:
    build:
      context: .
      target: builder
    env_file:
     - ./.env.docker
    entrypoint: ./entrypoint_celery.sh
    volumes:
     - ./media/:/app/app/static/media/
  web: 
    build:
      context: .
      target: builder
    depends_on:
      - db
      - redis
    env_file:
     - ./.env.docker
    volumes:
     - ./.gunicorn.conf.py:/app/gunicorn.conf.py
     - ./media/:/app/app/static/media/
    ports:
      - '8080:5000'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080


