"""keyword filter

Revision ID: 0b49f0997073
Revises: aaf434e9e7bf
Create Date: 2024-01-11 16:02:01.944862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b49f0997073'
down_revision = 'aaf434e9e7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filter_keyword')
    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filter_home', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('expire_after', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.drop_column('keywords')
        batch_op.drop_column('expire_after')
        batch_op.drop_column('filter_home')

    op.create_table('filter_keyword',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('filter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['filter_id'], ['filter.id'], name='filter_keyword_filter_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='filter_keyword_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='filter_keyword_pkey')
    )
    # ### end Alembic commands ###
