"""markdown editor optional

Revision ID: 2629cf0e2965
Revises: 1505d32771b7
Create Date: 2024-02-26 21:19:16.108520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2629cf0e2965'
down_revision = '1505d32771b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('markdown_editor', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('markdown_editor')

    # ### end Alembic commands ###
