"""local only communities

Revision ID: 328c9990e53e
Revises: b18ea0b841fe
Create Date: 2024-01-02 16:10:04.201183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328c9990e53e'
down_revision = 'b18ea0b841fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_only', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('local_only')

    # ### end Alembic commands ###
