"""report comments

Revision ID: 52789c4b1d0f
Revises: c12823f18553
Create Date: 2023-12-26 11:13:13.623630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52789c4b1d0f'
down_revision = 'c12823f18553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspect_post_reply_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'post_reply', ['suspect_post_reply_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('suspect_post_reply_id')

    # ### end Alembic commands ###
