"""longer file source_url

Revision ID: 62cbf0bf515a
Revises: d37fe77e043c
Create Date: 2024-02-13 06:50:03.712804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cbf0bf515a'
down_revision = 'd37fe77e043c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('source_url',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('source_url',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
