"""private mods

Revision ID: 755fa58fd603
Revises: feef49234599
Create Date: 2023-09-03 18:26:50.925553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755fa58fd603'
down_revision = 'feef49234599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_mods', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('private_mods')

    # ### end Alembic commands ###
