"""activitypub logging

Revision ID: 8885aafd5291
Revises: 0b49f0997073
Create Date: 2024-01-13 11:04:43.569931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8885aafd5291'
down_revision = '0b49f0997073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_activitypub_json', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('log_activitypub_json')

    # ### end Alembic commands ###
