"""community default layout

Revision ID: a4be1b198b0f
Revises: 6b4774eb6349
Create Date: 2024-01-21 14:22:02.450650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4be1b198b0f'
down_revision = '6b4774eb6349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_layout', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('default_layout')

    # ### end Alembic commands ###
