"""post vote index

Revision ID: aaf434e9e7bf
Revises: 5b4a967f9988
Create Date: 2024-01-10 10:17:47.397781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf434e9e7bf'
down_revision = '5b4a967f9988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_vote_effect'), ['effect'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_vote_effect'))

    # ### end Alembic commands ###
