"""save moderators url

Revision ID: b36dac7696d1
Revises: cae2e31293e8
Create Date: 2023-12-01 13:02:31.139428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36dac7696d1'
down_revision = 'cae2e31293e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ap_moderators_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('ap_moderators_url')

    # ### end Alembic commands ###
