"""index parent_id

Revision ID: d37fe77e043c
Revises: f19d761c216d
Create Date: 2024-02-09 15:14:13.274755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37fe77e043c'
down_revision = 'f19d761c216d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_reply', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_reply_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_reply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_reply_parent_id'))

    # ### end Alembic commands ###
