"""image-thumbnails

Revision ID: ee45b9ea4a0c
Revises: 4a3ca1701711
Create Date: 2023-11-27 20:53:29.624833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee45b9ea4a0c'
down_revision = '4a3ca1701711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_height', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_height')
        batch_op.drop_column('thumbnail_width')
        batch_op.drop_column('thumbnail_path')

    # ### end Alembic commands ###
