"""activitypub debug log

Revision ID: f032dbdfbd1d
Revises: cc98a471a1ad
Create Date: 2023-09-09 20:06:28.257769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f032dbdfbd1d'
down_revision = 'cc98a471a1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_pub_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('activity_json', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('exception_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_pub_log')
    # ### end Alembic commands ###
